name: myenv 
channels:
  - defaults  
dependencies:
  - python=3.12.2 
  - pandas=2.2.2  
  - numpy=1.26.4
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scikit-learn=1.5.1
  - xgboost=2.1.3
  - pickleshare=0.7.5
  - shap=0.46.0
 
